# Generated by Django 5.2.3 on 2025-06-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_movimientofinanciero_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10),
        ),
    ]
