# Generated by Django 5.2.3 on 2025-06-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
    ]
