# Generated by Django 5.2.3 on 2025-06-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=50),
        ),
    ]
