# Generated by Django 5.2.3 on 2025-06-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
